berkas = open("L200180154.txt", "w")
berkas.write("L200180154" "\n")
berkas.write("11/22/1999" "\n")
berkas.write("Aditya Dicky Kurniawan" "\n")
berkas.write("Surakarta")

berkas = open("L200180154.txt", "r")
NIM = berkas.readline()
Tanggal_Lahir = berkas.readline()
Nama = berkas.readline()
Kota = berkas.readline()
print(Nama)
print(Kota, Tanggal_Lahir)
print(NIM)
berkas.close()
